spring:
  application:
    name: admin-provider
# 端口号
server:
  port: 9601
# 服务注册与发现
eureka:
  client:
    service-url:
      defaultZone : http://pky:123@master:9501/eureka/,\
                    http://pky:123@slaves:9502/eureka/