spring:
  application:
    name: admin-consumer

server:
  port: 9602

eureka:
  client:
    service-url:
      defaultZone : http://pky:123@master:9501/eureka/,\
                    http://pky:123@slaves:9502/eureka/